Add update code

diff --git a/.github/workflows/demo-deploy-frontend.yaml b/.github/workflows/demo-deploy-frontend.yaml
--- a/.github/workflows/demo-deploy-frontend.yaml
+++ b/.github/workflows/demo-deploy-frontend.yaml
@@ -92,72 +92,87 @@ jobs:
           --image-uri ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:latest
           echo "Lambda image updated successfully"
 
-      # - name: Wait for Lambda update to finish
-      #   run: |
-      #     while true; do
-      #       STATUS=$(aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --query 'Configuration.LastUpdateStatus' --output text)
-      #       if [[ "$STATUS" == "Successful" ]]; then
-      #         echo "Lambda function update is complete."
-      #         break
-      #       else
-      #         echo "Lambda function update is in progress, waiting..."
-      #         sleep 10
-      #       fi
-      #     done
+      - name: Wait for Lambda update to finish
+        run: |
+          while true; do
+            STATUS=$(aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --query 'Configuration.LastUpdateStatus' --output text)
+            if [[ "$STATUS" == "Successful" ]]; then
+              echo "Lambda function update is complete."
+              break
+            else
+              echo "Lambda function update is in progress, waiting..."
+              sleep 10
+            fi
+          done
 
-      # - name: Publish new version for Lambda
-      #   run: |
-      #     LAMBDA_VERSION=$(aws lambda publish-version \
-      #       --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
-      #       --query 'Version' \
-      #       --output text)
-      #     echo "Lambda function published with version: $LAMBDA_VERSION"
+      - name: Publish new version for Lambda
+        run: |
+          LAMBDA_VERSION=$(aws lambda publish-version \
+            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
+            --query 'Version' \
+            --output text)
+          echo "Lambda function published with version: $LAMBDA_VERSION"
 
-      # - name: Wait for Lambda update to finish
-      #   run: |
-      #     while true; do
-      #       STATUS=$(aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --query 'Configuration.LastUpdateStatus' --output text)
-      #       if [[ "$STATUS" == "Successful" ]]; then
-      #         echo "Lambda function update is complete."
-      #         break
-      #       else
-      #         echo "Lambda function update is in progress, waiting..."
-      #         sleep 5
-      #       fi
-      #     done
+      - name: Wait for Lambda update to finish
+        run: |
+          while true; do
+            STATUS=$(aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --query 'Configuration.LastUpdateStatus' --output text)
+            if [[ "$STATUS" == "Successful" ]]; then
+              echo "Lambda function update is complete."
+              break
+            else
+              echo "Lambda function update is in progress, waiting..."
+              sleep 5
+            fi
+          done
 
-      # - name: Publish new version for Lambda
-      #   run: |
-      #     LAMBDA_VERSION=$(aws lambda publish-version \
-      #       --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
-      #       --query 'Version' \
-      #       --output text)
-      #     echo "Lambda function published with version: $LAMBDA_VERSION"
-      #     echo "LAMBDA_VERSION=$LAMBDA_VERSION" >> $GITHUB_ENV  # Save the version to GITHUB_ENV
+      - name: Publish new version for Lambda
+        run: |
+          LAMBDA_VERSION=$(aws lambda publish-version \
+            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
+            --query 'Version' \
+            --output text)
+          echo "Lambda function published with version: $LAMBDA_VERSION"
+          echo "LAMBDA_VERSION=$LAMBDA_VERSION" >> $GITHUB_ENV  # Save the version to GITHUB_ENV
 
-      # - name: Update Lambda Provisioned Concurrency and Alias with New Version
-      #   run: |
-      #     # Ensure that LAMBDA_VERSION is available
-      #     if [ -z "$LAMBDA_VERSION" ]; then
-      #       echo "Error: LAMBDA_VERSION is not set!"
-      #       exit 1
-      #     fi
+      - name: Update Lambda Provisioned Concurrency and Alias with New Version
+        run: |
+          # Ensure that LAMBDA_VERSION is available
+          if [ -z "$LAMBDA_VERSION" ]; then
+            echo "Error: LAMBDA_VERSION is not set!"
+            exit 1
+          fi
 
-      #     # Update or create provisioned concurrency for the alias
-      #     echo "Creating or updating provisioned concurrency for alias '${{ env.ENVIRONMENT }}' and version $LAMBDA_VERSION..."
-      #     aws lambda put-provisioned-concurrency-config \
-      #       --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
-      #       --qualifier ${{ env.ENVIRONMENT }} \
-      #       --provisioned-concurrent-executions ${{env.PROVISIONED-CONCURRENT-EXECUTIONS}}
-      #     echo "Provisioned concurrency created or updated for alias: ${{ env.ENVIRONMENT }}"
+          # Check if the alias exists
+          ALIAS_EXISTS=$(aws lambda get-alias \
+            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
+            --name ${{ env.ENVIRONMENT }} \
+            --query 'Name' --output text 2>/dev/null || echo "Alias not found")
 
-      #     # Update the alias to point to the new version
-      #     echo "Updating alias '${{ env.ENVIRONMENT }}' to point to new version: $LAMBDA_VERSION"
-      #     aws lambda update-alias \
-      #       --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
-      #       --name ${{ env.ENVIRONMENT }} \
-      #       --function-version $LAMBDA_VERSION
-      #     echo "Lambda alias '${{ env.ENVIRONMENT }}' updated to point to version: $LAMBDA_VERSION"
+          # If the alias exists, update it, otherwise create the alias
+          if [[ "$ALIAS_EXISTS" == "${{ env.ENVIRONMENT }}" ]]; then
+            echo "Alias '${{ env.ENVIRONMENT }}' exists. Updating alias to point to version $LAMBDA_VERSION..."
+            aws lambda update-alias \
+              --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
+              --name ${{ env.ENVIRONMENT }} \
+              --function-version $LAMBDA_VERSION
+            echo "Lambda alias '${{ env.ENVIRONMENT }}' updated to point to version: $LAMBDA_VERSION"
+          else
+            echo "Alias '${{ env.ENVIRONMENT }}' does not exist. Creating alias and pointing it to version $LAMBDA_VERSION..."
+            aws lambda create-alias \
+              --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
+              --name ${{ env.ENVIRONMENT }} \
+              --function-version $LAMBDA_VERSION
+            echo "Lambda alias '${{ env.ENVIRONMENT }}' created and pointing to version: $LAMBDA_VERSION"
+          fi
+
+          # Update or create provisioned concurrency for the alias
+          echo "Creating or updating provisioned concurrency for alias '${{ env.ENVIRONMENT }}' and version $LAMBDA_VERSION..."
+          aws lambda put-provisioned-concurrency-config \
+            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
+            --qualifier ${{ env.ENVIRONMENT }} \
+            --provisioned-concurrent-executions ${{ env.PROVISIONED-CONCURRENT-EXECUTIONS }}
+          echo "Provisioned concurrency created or updated for alias: ${{ env.ENVIRONMENT }}"
 
       - name: Upload static file to s3
         run: |
